name: Validate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  pylint:
    runs-on: ubuntu-latest
    name: Pylint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint homeassistant pyserial-asyncio

      - name: Run pylint
        run: |
          pylint custom_components/velolink/ --exit-zero

  black:
    runs-on: ubuntu-latest
    name: Code formatting (Black)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Black
        run: pip install black

      - name: Check formatting
        run: |
          black --check custom_components/velolink/
